#!/usr/bin/env bash
#
# Regenerate the nginx snippets describing Cloudflare's edge IP ranges.
#
# Writes into ops/nginx/ (no privileges needed) so the result is reviewable in git;
# installing them under /etc/nginx is a separate, explicit step — see below.
#
# Two snippets are produced from the same upstream list:
#   cloudflare-realip.conf — makes $remote_addr the real visitor IP (read from
#     CF-Connecting-IP, which Cloudflare always overwrites). Without it every
#     request looks like it comes from the edge, so per-IP rate limiting collapses
#     into a single shared bucket for the whole site.
#   cloudflare-geo.conf — sets $cf_edge=1 when the TCP peer is Cloudflare, so the
#     origin can refuse direct hits on the VPS IP and the WAF can't be skipped.
#     It deliberately tests $realip_remote_addr, not $remote_addr: the realip module
#     runs at the post-read phase, i.e. BEFORE access control, so by then
#     $remote_addr already holds the visitor's IP and matching it against Cloudflare
#     ranges would reject everyone. $realip_remote_addr keeps the original peer.
#     This is an http-context block — include it outside any server {}.
#
# Usage:
#   ops/scripts/update-cloudflare-ips.sh
#   sudo cp ops/nginx/cloudflare-*.conf /etc/nginx/snippets/
#   sudo nginx -t && sudo systemctl reload nginx
#
# Cloudflare changes these ranges rarely but does change them; re-run after an
# announcement, or from a monthly cron. Idempotent.

set -euo pipefail

OUT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../nginx" && pwd)"
REALIP="$OUT_DIR/cloudflare-realip.conf"
GEO="$OUT_DIR/cloudflare-geo.conf"

v4=$(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v4)
v6=$(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v6)

# Refuse to write a truncated list: too few ranges would break real-IP resolution
# and — through cloudflare-geo.conf — could lock legitimate traffic out.
ranges=$(printf '%s\n%s\n' "$v4" "$v6" | grep '/' || true)
count=$(printf '%s\n' "$ranges" | grep -c '/' || true)
if [[ "$count" -lt 10 ]]; then
  echo "Only $count ranges fetched — refusing to overwrite. Existing files left intact." >&2
  exit 1
fi

{
  echo "# Generated by ops/scripts/update-cloudflare-ips.sh — do not edit by hand."
  printf '%s\n' "$ranges" | sed 's/^/set_real_ip_from /; s/$/;/'
  echo "real_ip_header CF-Connecting-IP;"
} > "$REALIP"

{
  echo "# Generated by ops/scripts/update-cloudflare-ips.sh — do not edit by hand."
  echo "# http-context block: include it OUTSIDE any server {}."
  echo "geo \$realip_remote_addr \$cf_edge {"
  echo "    default 0;"
  printf '%s\n' "$ranges" | sed 's/^/    /; s/$/ 1;/'
  echo "    127.0.0.1/32 1;   # local smoke tests"
  echo "    ::1/128 1;"
  echo "}"
} > "$GEO"

echo "Wrote $count ranges to:"
echo "  $REALIP"
echo "  $GEO"
echo
echo "Install with:"
echo "  sudo cp $OUT_DIR/cloudflare-*.conf /etc/nginx/snippets/"
echo "  sudo nginx -t && sudo systemctl reload nginx"
